[theme]
primaryColor = '#64ffda'
backgroundColor = '#0a192f'
secondaryBackgroundColor = '#112240'
textColor = '#FFFFFF'
font = "monospace"

[server]
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false